#!/usr/bin/env bash

if [ "$#" != "1" ]
then
  echo "Usage: $0 firmware.hex"
  exit 1
fi
simulator $1 &
enumerate > "enumerate-${1}.log" 2> "enumerate-${1}.err.log" &
sleep 10
#killall python3
#killall simulator
simulator $1 &
middleware > "middleware-${1}.log" 2> "middleware-${1}.err.log" &
sleep 10
#killall python3
#killall simulator